export type FeatureValue = boolean | string;

export interface FeatureCategory {
  name: string;
  features: { name: string; key: string }[];
}

export interface LicenseInfo {
  displayName: string;
  skuPartNumber: string;
  costPerMonth: number;
  category: "Suite" | "Add-on" | "Standalone";
  description: string;
  features: Record<string, FeatureValue>;
}

export const FEATURE_CATEGORIES: FeatureCategory[] = [
  {
    name: "Core Office Apps",
    features: [
      { name: "Word", key: "word" },
      { name: "Excel", key: "excel" },
      { name: "PowerPoint", key: "powerpoint" },
      { name: "Outlook", key: "outlook" },
      { name: "OneNote", key: "onenote" },
      { name: "Access (PC only)", key: "access" },
      { name: "Desktop app install", key: "desktopApps" },
      { name: "Web & mobile apps", key: "webMobileApps" },
    ],
  },
  {
    name: "Email & Calendar",
    features: [
      { name: "Mailbox size", key: "mailboxSize" },
      { name: "Custom domain email", key: "customDomain" },
      { name: "Shared mailboxes", key: "sharedMailboxes" },
      { name: "Exchange Online Archiving", key: "archiving" },
      { name: "Resource mailboxes", key: "resourceMailboxes" },
      { name: "Calendar sharing", key: "calendarSharing" },
      { name: "Focused Inbox", key: "focusedInbox" },
    ],
  },
  {
    name: "Communication & Collaboration",
    features: [
      { name: "Microsoft Teams", key: "teams" },
      { name: "Teams meetings (max duration)", key: "teamsMeetingDuration" },
      { name: "Teams meeting capacity", key: "teamsMeetingCapacity" },
      { name: "Teams webinars", key: "teamsWebinars" },
      { name: "Teams Phone System", key: "teamsPhoneSystem" },
      { name: "Audio Conferencing", key: "audioConferencing" },
      { name: "SharePoint", key: "sharepoint" },
      { name: "Yammer / Viva Engage", key: "yammer" },
      { name: "Microsoft Loop", key: "loop" },
    ],
  },
  {
    name: "Storage",
    features: [
      { name: "OneDrive storage per user", key: "oneDriveStorage" },
      { name: "SharePoint storage (tenant)", key: "sharepointStorage" },
    ],
  },
  {
    name: "Security & Identity",
    features: [
      { name: "Multi-Factor Authentication (MFA)", key: "mfa" },
      { name: "Conditional Access", key: "conditionalAccess" },
      { name: "Microsoft Entra ID plan", key: "entraIdPlan" },
      { name: "Microsoft Intune", key: "intune" },
      { name: "Microsoft Defender for Office 365", key: "defenderOffice365" },
      { name: "Microsoft Defender for Endpoint", key: "defenderEndpoint" },
      { name: "Microsoft Defender for Identity", key: "defenderIdentity" },
      { name: "Microsoft Defender for Cloud Apps", key: "defenderCloudApps" },
      { name: "Azure Information Protection", key: "aip" },
      { name: "Windows Hello / Passwordless", key: "passwordless" },
    ],
  },
  {
    name: "Compliance & Data Governance",
    features: [
      { name: "Data Loss Prevention (DLP)", key: "dlp" },
      { name: "eDiscovery", key: "ediscovery" },
      { name: "Advanced eDiscovery", key: "advancedEdiscovery" },
      { name: "Retention policies", key: "retentionPolicies" },
      { name: "Sensitivity labels", key: "sensitivityLabels" },
      { name: "Insider Risk Management", key: "insiderRisk" },
      { name: "Communication Compliance", key: "communicationCompliance" },
      { name: "Information Barriers", key: "informationBarriers" },
      { name: "Customer Lockbox", key: "customerLockbox" },
      { name: "Privileged Access Management", key: "privilegedAccess" },
    ],
  },
  {
    name: "Automation & Development",
    features: [
      { name: "Power Automate", key: "powerAutomate" },
      { name: "Power Apps", key: "powerApps" },
      { name: "Power BI", key: "powerBI" },
      { name: "Power Virtual Agents", key: "powerVirtualAgents" },
      { name: "Microsoft Forms", key: "forms" },
      { name: "Microsoft Lists", key: "lists" },
      { name: "Microsoft Planner", key: "planner" },
      { name: "Microsoft To Do", key: "todo" },
      { name: "Microsoft Bookings", key: "bookings" },
    ],
  },
  {
    name: "AI & Advanced",
    features: [
      { name: "Microsoft 365 Copilot eligible", key: "copilotEligible" },
      { name: "Microsoft Viva Insights", key: "vivaInsights" },
      { name: "Microsoft Viva Learning", key: "vivaLearning" },
      { name: "Windows Enterprise license", key: "windowsEnterprise" },
    ],
  },
];

export const LICENSES: LicenseInfo[] = [
  {
    displayName: "Microsoft 365 E5",
    skuPartNumber: "SPE_E5",
    costPerMonth: 57,
    category: "Suite",
    description: "The most comprehensive plan with advanced security, compliance, voice, and analytics capabilities.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "100 GB", customDomain: true, sharedMailboxes: true, archiving: true,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: true, teamsPhoneSystem: true, audioConferencing: true,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "5 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: true, entraIdPlan: "P2",
      intune: true, defenderOffice365: "Plan 2", defenderEndpoint: "Plan 2",
      defenderIdentity: true, defenderCloudApps: true, aip: "P2", passwordless: true,
      dlp: true, ediscovery: true, advancedEdiscovery: true,
      retentionPolicies: true, sensitivityLabels: true,
      insiderRisk: true, communicationCompliance: true,
      informationBarriers: true, customerLockbox: true, privilegedAccess: true,
      powerAutomate: "Included", powerApps: "Included", powerBI: "Power BI Pro included",
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Premium",
      vivaLearning: true, windowsEnterprise: true,
    },
  },
  {
    displayName: "Microsoft 365 E3",
    skuPartNumber: "SPE_E3",
    costPerMonth: 36,
    category: "Suite",
    description: "Enterprise productivity and security with desktop apps, advanced compliance, and information protection.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "100 GB", customDomain: true, sharedMailboxes: true, archiving: true,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: true, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "5 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: true, entraIdPlan: "P1",
      intune: true, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: "P1", passwordless: true,
      dlp: true, ediscovery: true, advancedEdiscovery: false,
      retentionPolicies: true, sensitivityLabels: true,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Included", powerApps: "Included", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Basic",
      vivaLearning: true, windowsEnterprise: true,
    },
  },
  {
    displayName: "Office 365 E5",
    skuPartNumber: "ENTERPRISEPREMIUM",
    costPerMonth: 38,
    category: "Suite",
    description: "Advanced Office 365 with phone system, audio conferencing, and advanced analytics — no Windows or EMS.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "100 GB", customDomain: true, sharedMailboxes: true, archiving: true,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: true, teamsPhoneSystem: true, audioConferencing: true,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "5 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: "Plan 2", defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: true, ediscovery: true, advancedEdiscovery: true,
      retentionPolicies: true, sensitivityLabels: true,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Included", powerApps: "Included", powerBI: "Power BI Pro included",
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Basic",
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Office 365 E3",
    skuPartNumber: "ENTERPRISEPACK",
    costPerMonth: 23,
    category: "Suite",
    description: "Desktop Office apps, enterprise email, and collaboration tools without Windows or EMS add-ons.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "100 GB", customDomain: true, sharedMailboxes: true, archiving: true,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "5 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: true, ediscovery: true, advancedEdiscovery: false,
      retentionPolicies: true, sensitivityLabels: "Manual only",
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Included", powerApps: "Included", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Basic",
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Office 365 E1",
    skuPartNumber: "STANDARDPACK",
    costPerMonth: 10,
    category: "Suite",
    description: "Web-based Office apps, email, and collaboration essentials for frontline and information workers.",
    features: {
      word: "Web only", excel: "Web only", powerpoint: "Web only", outlook: "Web only", onenote: "Web only", access: false,
      desktopApps: false, webMobileApps: true,
      mailboxSize: "50 GB", customDomain: true, sharedMailboxes: true, archiving: false,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "1 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: "Basic", advancedEdiscovery: false,
      retentionPolicies: "Basic", sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Limited", powerApps: "Limited", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Microsoft 365 F1",
    skuPartNumber: "SPE_F1",
    costPerMonth: 2.25,
    category: "Suite",
    description: "Purpose-built for frontline workers with limited email (2 GB) and web/mobile app access.",
    features: {
      word: "Web/mobile only", excel: "Web/mobile only", powerpoint: "Web/mobile only",
      outlook: "Web/mobile only", onenote: "Web/mobile only", access: false,
      desktopApps: false, webMobileApps: true,
      mailboxSize: "2 GB", customDomain: true, sharedMailboxes: true, archiving: false,
      resourceMailboxes: false, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "1,000",
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: "Read-only", yammer: true, loop: false,
      oneDriveStorage: "2 GB", sharepointStorage: "Shared tenant pool",
      mfa: true, conditionalAccess: true, entraIdPlan: "P1",
      intune: true, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: "P1", passwordless: true,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: "View only",
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Limited", powerApps: "Limited", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: true, windowsEnterprise: true,
    },
  },
  {
    displayName: "Microsoft 365 Business Premium",
    skuPartNumber: "SPB",
    costPerMonth: 22,
    category: "Suite",
    description: "Best-value plan for SMBs up to 300 users with desktop apps, advanced security, and device management.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "50 GB", customDomain: true, sharedMailboxes: true, archiving: true,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "300",
      teamsWebinars: true, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "1 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: true, entraIdPlan: "P1",
      intune: true, defenderOffice365: "Plan 1", defenderEndpoint: "Plan 1",
      defenderIdentity: false, defenderCloudApps: false, aip: "P1", passwordless: true,
      dlp: true, ediscovery: true, advancedEdiscovery: false,
      retentionPolicies: true, sensitivityLabels: true,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Included", powerApps: "Included", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Basic",
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Microsoft 365 Business Standard",
    skuPartNumber: "O365_BUSINESS_PREMIUM",
    costPerMonth: 12.50,
    category: "Suite",
    description: "Desktop apps and cloud services for SMBs — no advanced security or device management.",
    features: {
      word: true, excel: true, powerpoint: true, outlook: true, onenote: true, access: true,
      desktopApps: true, webMobileApps: true,
      mailboxSize: "50 GB", customDomain: true, sharedMailboxes: true, archiving: false,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "300",
      teamsWebinars: true, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "1 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Included", powerApps: "Included", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: "Basic",
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Microsoft 365 Business Basic",
    skuPartNumber: "O365_BUSINESS_ESSENTIALS",
    costPerMonth: 6,
    category: "Suite",
    description: "Web-based Office apps with email, Teams, and cloud storage for small businesses.",
    features: {
      word: "Web only", excel: "Web only", powerpoint: "Web only", outlook: "Web only",
      onenote: "Web only", access: false,
      desktopApps: false, webMobileApps: true,
      mailboxSize: "50 GB", customDomain: true, sharedMailboxes: true, archiving: false,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: true, teamsMeetingDuration: "30 hours", teamsMeetingCapacity: "300",
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: true, yammer: true, loop: true,
      oneDriveStorage: "1 TB", sharepointStorage: "1 TB + 10 GB/user",
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: "Limited", powerApps: "Limited", powerBI: false,
      powerVirtualAgents: false, forms: true, lists: true, planner: true, todo: true, bookings: true,
      copilotEligible: true, vivaInsights: false,
      vivaLearning: true, windowsEnterprise: false,
    },
  },
  {
    displayName: "Microsoft 365 Copilot",
    skuPartNumber: "Microsoft_365_Copilot",
    costPerMonth: 30,
    category: "Add-on",
    description: "AI-powered assistant integrated across Word, Excel, PowerPoint, Outlook, and Teams. Requires eligible base license.",
    features: {
      word: "Copilot AI assist", excel: "Copilot AI assist", powerpoint: "Copilot AI assist",
      outlook: "Copilot AI assist", onenote: false, access: false,
      desktopApps: false, webMobileApps: false,
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: "Copilot in Teams", teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: "Copilot in Loop",
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: "This is Copilot", vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Exchange Online Plan 1",
    skuPartNumber: "EXCHANGESTANDARD",
    costPerMonth: 4,
    category: "Standalone",
    description: "Business email with 50 GB mailbox, calendar, and contacts — no Office apps included.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: "Web only", onenote: false, access: false,
      desktopApps: false, webMobileApps: false,
      mailboxSize: "50 GB", customDomain: true, sharedMailboxes: true, archiving: false,
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: "Basic", advancedEdiscovery: false,
      retentionPolicies: "Basic", sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Exchange Online Plan 2",
    skuPartNumber: "EXCHANGEENTERPRISE",
    costPerMonth: 8,
    category: "Standalone",
    description: "Advanced email with 100 GB mailbox, unlimited archiving, DLP, and hosted voicemail.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: "Web only", onenote: false, access: false,
      desktopApps: false, webMobileApps: false,
      mailboxSize: "100 GB", customDomain: true, sharedMailboxes: true, archiving: "Unlimited",
      resourceMailboxes: true, calendarSharing: true, focusedInbox: true,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: true, conditionalAccess: false, entraIdPlan: "Free",
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: true, ediscovery: true, advancedEdiscovery: false,
      retentionPolicies: true, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Visio Plan 2",
    skuPartNumber: "VISIOCLIENT",
    costPerMonth: 15,
    category: "Add-on",
    description: "Professional diagramming with desktop and web apps for flowcharts, org charts, and floor plans.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "Visio desktop", webMobileApps: "Visio web",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Project Plan 5",
    skuPartNumber: "PROJECTPREMIUM",
    costPerMonth: 55,
    category: "Add-on",
    description: "Full project and portfolio management with desktop app, resource management, and demand management.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "Project desktop", webMobileApps: "Project web",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: "Advanced", todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Project Plan 3",
    skuPartNumber: "PROJECTPROFESSIONAL",
    costPerMonth: 30,
    category: "Add-on",
    description: "Project management with desktop app, timesheets, and resource management for project managers.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "Project desktop", webMobileApps: "Project web",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: "Advanced", todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Power BI Pro",
    skuPartNumber: "POWER_BI_PRO",
    costPerMonth: 10,
    category: "Add-on",
    description: "Self-service business intelligence with interactive visualizations, sharing, and collaboration.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "Power BI Desktop", webMobileApps: "Power BI web/mobile",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: "Pro",
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "Power BI Premium Per User",
    skuPartNumber: "POWER_BI_PREMIUM_PER_USER",
    costPerMonth: 20,
    category: "Add-on",
    description: "Premium analytics with AI, paginated reports, dataflows, and larger dataset capacity per user.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "Power BI Desktop", webMobileApps: "Power BI web/mobile",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: "Premium Per User",
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
  {
    displayName: "GitHub Copilot",
    skuPartNumber: "GITHUB_COPILOT",
    costPerMonth: 20,
    category: "Add-on",
    description: "AI-powered code suggestions and completions for developers across popular IDEs.",
    features: {
      word: false, excel: false, powerpoint: false, outlook: false, onenote: false, access: false,
      desktopApps: "IDE extensions", webMobileApps: "github.com",
      mailboxSize: false, customDomain: false, sharedMailboxes: false, archiving: false,
      resourceMailboxes: false, calendarSharing: false, focusedInbox: false,
      teams: false, teamsMeetingDuration: false, teamsMeetingCapacity: false,
      teamsWebinars: false, teamsPhoneSystem: false, audioConferencing: false,
      sharepoint: false, yammer: false, loop: false,
      oneDriveStorage: false, sharepointStorage: false,
      mfa: false, conditionalAccess: false, entraIdPlan: false,
      intune: false, defenderOffice365: false, defenderEndpoint: false,
      defenderIdentity: false, defenderCloudApps: false, aip: false, passwordless: false,
      dlp: false, ediscovery: false, advancedEdiscovery: false,
      retentionPolicies: false, sensitivityLabels: false,
      insiderRisk: false, communicationCompliance: false,
      informationBarriers: false, customerLockbox: false, privilegedAccess: false,
      powerAutomate: false, powerApps: false, powerBI: false,
      powerVirtualAgents: false, forms: false, lists: false, planner: false, todo: false, bookings: false,
      copilotEligible: false, vivaInsights: false,
      vivaLearning: false, windowsEnterprise: false,
    },
  },
];

export function getLicenseByName(name: string): LicenseInfo | undefined {
  return LICENSES.find((l) => l.displayName === name);
}

export function getLicensesBySku(sku: string): LicenseInfo | undefined {
  return LICENSES.find((l) => l.skuPartNumber === sku);
}

export function getSuiteLicenses(): LicenseInfo[] {
  return LICENSES.filter((l) => l.category === "Suite");
}

export function getAddonLicenses(): LicenseInfo[] {
  return LICENSES.filter((l) => l.category !== "Suite");
}
